Repository projetoKhali/API2Semestre, pull requests merged in 2023-04, with the labels that each got.

#63 atualização de tabelas
  .gitignore
  SQL/tabelas.sql
  SQL/views.sql
  src/main/java/org/openjfx/API2Semestre/JavaFiles/SQLConnection.java
Labels: Low-Impact

#64 Update Issue & Pull Request templates
  .github/ISSUE_TEMPLATE.md
  .github/pull_request_template.md
  .info
Labels: documentation, Low-Impact

#67 Listagem
  .gitignore
  .info
  .vscode/launch.json
  .vscode/settings.json
  SQL/tabelas.sql
  SQL/views.sql
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/openjfx/API2Semestre/App.java
  src/main/java/org/openjfx/API2Semestre/Classes/Appointment.java
  src/main/java/org/openjfx/API2Semestre/Classes/AppointmentType.java
  src/main/java/org/openjfx/API2Semestre/Classes/Permission.java
  src/main/java/org/openjfx/API2Semestre/Classes/Status.java
  src/main/java/org/openjfx/API2Semestre/InputMethods.java
  src/main/java/org/openjfx/API2Semestre/PrimaryController.java
  src/main/java/org/openjfx/API2Semestre/custom_tags/Permission.fxml
  src/main/java/org/openjfx/API2Semestre/custom_tags/Permission.java
  src/main/java/org/openjfx/API2Semestre/custom_tags/ViewConfig.fxml
  src/main/java/org/openjfx/API2Semestre/custom_tags/ViewConfig.java
  src/main/java/org/openjfx/API2Semestre/data_utils/DateConverter.java
  src/main/java/org/openjfx/API2Semestre/database/QueryLibs.java
  src/main/java/org/openjfx/API2Semestre/database/SQLConnection.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/AppointmentsController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ApprovalsController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ApprovePopupListItem.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ListagemAdmController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/PopUpFeedbackController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/PopupCallbackHandler.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/PopupController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/RejectPopupListItem.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/approvePopupListItem.fxml
  src/main/java/org/openjfx/API2Semestre/view_controllers/popUpFeedback.fxml
  src/main/java/org/openjfx/API2Semestre/view_controllers/rejectPopupListItem.fxml
  src/main/java/org/openjfx/API2Semestre/view_macros/TableCheckBoxMacros.java
  src/main/java/org/openjfx/API2Semestre/view_macros/TableColumnFilterMacros.java
  src/main/java/org/openjfx/API2Semestre/view_utils/AppointmentFilter.java
  src/main/java/org/openjfx/API2Semestre/view_utils/AppointmentWrapper.java
  src/main/java/org/openjfx/API2Semestre/view_utils/HasSelectedProperty.java
  src/main/java/org/openjfx/API2Semestre/view_utils/PrettyTableCell.java
  src/main/java/org/openjfx/API2Semestre/view_utils/PrettyTableCellInstruction.java
  src/main/resources/org/openjfx/API2Semestre/reserva.fxml.fxml
  src/main/resources/org/openjfx/api2semestre/appointments.fxml
  src/main/resources/org/openjfx/api2semestre/approvals.fxml
  src/main/resources/org/openjfx/api2semestre/listagemAdm.fxml
Labels: enhancement, Back-End, Front-End, Key Feature, High-Impact

#65 Atualização do diagrama de Entidades
  Docs/ERD/Diagrama - Banco de Dados para Apontamento de Horas.png
  Docs/ERD/Diagrama de Cardinalidade.png
  Docs/ERD/Entidade-Relacionamento.drawio.png
  README.md
  SQL/tabelas.sql
Labels: documentation, Low-Impact

#73 Revert "update viewButtonTemplate.fxml"
  .gitignore
  src/main/resources/org/openjfx/api2semestre/viewButtonTemplate.fxml
Labels: bug
