Repository projetoKhali/API2Semestre, pull requests merged in 2023-05, with the labels that each got.

#89 Adicionado tela e controller de cadastro de usuário
  src/main/java/org/openjfx/API2Semestre/view_controllers/UserRegisterController.java
  src/main/resources/org/openjfx/api2semestre/views/userRegister.fxml
Labels: Front-End, Low-Impact

#98 Cadastro de Centro de Resultado
  .vscode/launch.json
  SQL/tabelas.sql
  SQL/views.sql
  pom.xml
  src/main/java/module-info.java
  src/main/java/org/openjfx/API2Semestre/App.java
  src/main/java/org/openjfx/API2Semestre/authentication/User.java
  src/main/java/org/openjfx/API2Semestre/custom_tags/LookupTextField.java
  src/main/java/org/openjfx/API2Semestre/data/MemberRelation.java
  src/main/java/org/openjfx/API2Semestre/data/ResultCenter.java
  src/main/java/org/openjfx/API2Semestre/data/ResultsCenter.java
  src/main/java/org/openjfx/API2Semestre/database/Data.java
  src/main/java/org/openjfx/API2Semestre/database/QueryLibs.java
  src/main/java/org/openjfx/API2Semestre/database/query/Query.java
  src/main/java/org/openjfx/API2Semestre/database/query/QueryTable.java
  src/main/java/org/openjfx/API2Semestre/database/query/TableProperty.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/AppointmentsController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ApprovalsController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ListagemAdmController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ResultCenterController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/login/LoginAdm.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/login/LoginCol.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/login/LoginGes.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/login/ProvisoryLogin.java
  src/main/java/org/openjfx/API2Semestre/view_macros/TableColumnFilterMacros.java
  src/main/java/org/openjfx/API2Semestre/view_utils/AppointmentWrapper.java
  src/main/java/org/openjfx/API2Semestre/view_utils/filters/AppointmentFilter.java
  src/main/java/org/openjfx/API2Semestre/view_utils/filters/ResultCenterFilter.java
  src/main/java/org/openjfx/API2Semestre/views_manager/View.java
  src/main/resources/org/openjfx/api2semestre/views/resultCenters.fxml
Labels: enhancement, Back-End, Key Feature

#102 Tela `Relatórios`
  .vscode/settings.json
  src/main/java/org/openjfx/API2Semestre/App.java
  src/main/java/org/openjfx/API2Semestre/authentication/Permission.java
  src/main/java/org/openjfx/API2Semestre/database/QueryLibs.java
  src/main/java/org/openjfx/API2Semestre/report/ReportExporter.java
  src/main/java/org/openjfx/API2Semestre/report/ReportInterval.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ApprovalsController.java
  src/main/java/org/openjfx/API2Semestre/view_controllers/ReportController.java
  src/main/java/org/openjfx/API2Semestre/view_utils/IntervalFilter.java
  src/main/java/org/openjfx/API2Semestre/view_utils/ReportIntervalWrapper.java
  src/main/java/org/openjfx/API2Semestre/views_manager/View.java
  src/main/resources/org/openjfx/api2semestre/views/report.fxml
Labels: Front-End, Provisional
